language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

script:
  - mdbook build "C:\Users\qbisi\OneDrive\Desktop\Note" && mdbook test "C:\Users\qbisi\OneDrive\Desktop\Note"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: C:\Users\qbisi\OneDrive\Desktop\Note\book
  keep-history: false
  on:
    branch: master